version: '3.8'

services:
  production:
    build:
      context: .
      target: production
    environment:
      - PYTHONDONTWRITEBYTECODE=1
    ports:
      - "8000:8000"
    command: sh -c "flask db upgrade && python3 seed.py && gunicorn --bind 0.0.0.0:8000 app:app"
    depends_on:
      - db
    env_file:
      - .env 

