version: '3.8'

services:
  db:
    image: mysql:5.7
    platform: linux/x86_64
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"

  app:
    build:
      context: .
      target: development
    environment:
      - FLASK_ENV=development
      - PYTHONDONTWRITEBYTECODE=1
    ports:
      - "3333:3333"
    volumes:
      - .:/app
    command: sh -c "flask db upgrade && python3 main.py"
    depends_on:
      - db
    env_file:
      - .env 
