"""empty message

Revision ID: 26b2e598740b
Revises: 6c607649ed86
Create Date: 2023-12-16 20:26:26.355124

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "26b2e598740b"
down_revision = "6c607649ed86"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("transaction", schema=None) as batch_op:
        batch_op.drop_column("type")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("transaction", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("type", mysql.ENUM("CREDIT", "DEBIT"), nullable=False)
        )

    # ### end Alembic commands ###
