"""empty message

Revision ID: 66ffaa7da657
Revises: f160e412467c
Create Date: 2023-12-15 01:25:02.763708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "66ffaa7da657"
down_revision = "f160e412467c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("account", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "type",
                sa.Enum("CURRENT", "SAVINGS", name="accounttypeenum"),
                nullable=True,
            )
        )
        batch_op.add_column(sa.Column("created_at", sa.DateTime(), nullable=True))

    with op.batch_alter_table("person", schema=None) as batch_op:
        batch_op.add_column(sa.Column("created_at", sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("person", schema=None) as batch_op:
        batch_op.drop_column("created_at")

    with op.batch_alter_table("account", schema=None) as batch_op:
        batch_op.drop_column("created_at")
        batch_op.drop_column("type")

    # ### end Alembic commands ###
