"""empty message

Revision ID: 6807627cd569
Revises: 26b2e598740b
Create Date: 2023-12-17 19:28:20.784751

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "6807627cd569"
down_revision = "26b2e598740b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("account", schema=None) as batch_op:
        batch_op.alter_column(
            "type",
            existing_type=mysql.ENUM("CURRENT", "SAVINGS"),
            type_=sa.Integer(),
            existing_nullable=True,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("account", schema=None) as batch_op:
        batch_op.alter_column(
            "type",
            existing_type=sa.Integer(),
            type_=mysql.ENUM("CURRENT", "SAVINGS"),
            existing_nullable=True,
        )

    # ### end Alembic commands ###
